from __future__ import annotations

import re
from urllib.parse import urljoin, urlsplit, urlunsplit, parse_qsl, urlencode

from bs4 import BeautifulSoup, Tag

from .credentials import Credentials
from .moodle_api import MoodleAPI


class CourseSections:
    """Manage Moodle course sections through the same forms as the UI."""

    def __init__(self, course: str):
        self.credentials = Credentials.load_credentials()
        self.credentials.set_course(course)
        self.api = MoodleAPI()
        self.base_url = self.api.urlHandler.base()
        self.api.open_url(self.api.urlHandler.course())
        page = self.api.browser.page
        edit_link = self._link_by_text(page, "Ativar edição")
        if edit_link is not None:
            self.api.open_url(urljoin(self.base_url, edit_link["href"]))
        self._require_edit_actions(self.api.browser.page)

    @staticmethod
    def _link_by_text(page: BeautifulSoup, text: str) -> Tag | None:
        return next(
            (
                link
                for link in page.select("a[href]")
                if link.get_text(" ", strip=True) == text
            ),
            None,
        )

    @staticmethod
    def _require_edit_actions(page: BeautifulSoup) -> None:
        if not page.select_one("a.add-sections[href]") and not page.select_one(
            'a[href*="/course/editsection.php"]'
        ):
            raise PermissionError(
                "Course editing is unavailable for this account or course."
            )

    @staticmethod
    def _section_index(node: Tag) -> int | None:
        match = re.fullmatch(r"section-(\d+)", str(node.get("id", "")))
        return int(match.group(1)) if match else None

    def _section_node(self, index: int) -> Tag:
        page = self.api.browser.page
        node = page.find(id=f"section-{index}")
        if not isinstance(node, Tag):
            raise ValueError(f"Section {index} was not found in this course.")
        return node

    def _section_name(self, node: Tag) -> str:
        title = node.select_one(".sectionname")
        if title is None:
            title = node.select_one("[data-region=sectionname]")
        return title.get_text(" ", strip=True) if title is not None else ""

    def section_info(self, index: int) -> tuple[int, str]:
        node = self._section_node(index)
        return index, self._section_name(node)

    def _edit_link(self, node: Tag) -> Tag:
        link = node.select_one('a[href*="/course/editsection.php"]')
        if not isinstance(link, Tag):
            raise PermissionError(f"Section {self._section_index(node)} cannot be edited.")
        return link

    def _rename_node(self, node: Tag, name: str) -> None:
        link = self._edit_link(node)
        self.api.open_url(urljoin(self.base_url, link["href"]))
        form = self.api.browser.page.select_one("form")
        if not isinstance(form, Tag) or form.find("input", {"name": "name[value]"}) is None:
            raise RuntimeError("Moodle's section edit form was not found.")

        self.api.browser.select_form(nr=0)
        self.api.browser["name[customize]"] = "1"
        self.api.browser["name[value]"] = name
        self.api.browser.submit_selected()

    def rename(self, index: int, name: str) -> str:
        if not name.strip():
            raise ValueError("Section name cannot be empty.")
        node = self._section_node(index)
        self._rename_node(node, name.strip())
        return name.strip()

    def add(self, name: str | None = None) -> tuple[int, str]:
        if name is not None and not name.strip():
            raise ValueError("Section name cannot be empty.")
        page = self.api.browser.page
        indexes = [
            index
            for node in page.select("li.section[id]")
            if (index := self._section_index(node)) is not None
        ]
        add_link = page.select_one("a.add-sections[href]")
        if not isinstance(add_link, Tag):
            raise PermissionError("Moodle did not provide an add-section control.")

        # This is the same sesskey-protected request generated by Moodle's UI.
        self.api.open_url(urljoin(self.base_url, add_link["href"]))
        new_page = self.api.browser.page
        created_indexes = [
            index
            for node in new_page.select("li.section[id]")
            if (index := self._section_index(node)) is not None
        ]
        new_indexes = sorted(set(created_indexes) - set(indexes))
        if not new_indexes:
            raise RuntimeError("Moodle did not show a newly created section.")
        new_index = new_indexes[0]

        if name is not None:
            node = self._section_node(new_index)
            self._rename_node(node, name)

        node = self._section_node(new_index)
        return new_index, self._section_name(node)

    def remove(self, index: int) -> str:
        node = self._section_node(index)
        name = self._section_name(node)
        edit_link = self._edit_link(node)
        parts = urlsplit(urljoin(self.base_url, edit_link["href"]))
        query = parse_qsl(parts.query, keep_blank_values=True)
        query.append(("delete", "1"))
        delete_url = urlunsplit(
            (parts.scheme, parts.netloc, parts.path, urlencode(query), "")
        )
        self.api.open_url(delete_url)

        confirm_form = next(
            (
                form
                for form in self.api.browser.page.select("form")
                if form.find("input", {"name": "confirm"}) is not None
                and form.find("input", {"name": "delete"}) is not None
            ),
            None,
        )
        if not isinstance(confirm_form, Tag):
            raise RuntimeError("Moodle's section deletion confirmation was not found.")

        forms = self.api.browser.page.select("form")
        confirm_form_index = next(
            index for index, form in enumerate(forms) if form is confirm_form
        )
        self.api.browser.select_form(nr=confirm_form_index)
        self.api.browser.submit_selected()
        return name

    def close(self) -> None:
        self.api.browser.close()
